name = "shipide-portal-api"
main = "worker.shopify.js"
compatibility_date = "2026-02-23"
compatibility_flags = ["nodejs_compat"]
workers_dev = true

[triggers]
crons = ["15 6 * * *"]

[browser]
binding = "BROWSER"

[vars]
SUPABASE_URL = "https://pxcqxubehvnyaubqjcrf.supabase.co"
SUPABASE_PUBLISHABLE_KEY = "sb_publishable_MfL9s44GmmR9peD1jouetw_aZOa8xVa"
SHOPIFY_API_VERSION = "2025-10"
SHOPIFY_SCOPES = "read_orders,read_locations"
WIX_APP_ID = "8696f8e6-5726-42c0-b8fd-1b68e6a0fa18"
WIX_APP_INSTALL_URL = "https://wix.to/NXTv6Vw"
DATA_CLEANER_SUBMISSION_EMAIL = "shipextract@shipide.com"
